#!/bin/sh
# Login shell initialization file
# Profile file. Runs on login. Environmental variables are set here.


# Add '~/.local/bin' to $PATH
	export PATH="$HOME/.local/bin:$PATH"
	export PATH="$HOME/.local/bin/statusbar:$PATH"
#	export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

	unsetopt PROMPT_SP

    # Default programs:
	export EDITOR="nvim"
	export TERMINAL="st"
	export BROWSER="firefox"


# ~/ Clean-up
         export XDG_CONFIG_HOME="$HOME/.config"
         export XDG_DATA_HOME="$HOME/.local/share"
         export XDG_CACHE_HOME="$HOME/.cache"
	     export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
	     export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
	     export HISTFILE="$XDG_DATA_HOME/history"
	     export ZDOTDIR=$HOME/.config/zsh
	     export TMUX_TMPDIR="XDG_RUNTIME_DIR"
#L	     export GOPATH="$XDG_DATA_HOME/go"
#L	     export CARGO_HOME="$XDG_DATA_HOME/cargo"
#L	     export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
#L	     export UNISON="$XDG_DATA_HOME/unison"

#toInstall   export MBSYNCRC			= "$XDG_CONFIG_HOME/mbsync/config"
#toInstall   export NOTMUCH_CONFIG		= "$XDG_CONFIG_HOME/notmuch-config"
#toInstall   export WGETRC			= "$XDG_CONFIG_HOME/wget/wgetrc"
#toInstall   export WINEPREFIX			= "$XDG_DATA_HOME/wineprefixes/default"
	     export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

    # Inputrc - handles keyboard mapping for specific situations.
	     export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"

# Other program settings:
#L	export DICS="/usr/share/stardict/dic/"
	export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
	export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
#L	export QT_QPA_PLATFORMTHEME="gtk2" 	# Have QT use gtk2 theme
	export MOZ_USE_XINPUT2="1" 		# Mozilla smooth scrolling/touchpads
#L	export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
#L	export _JAVA_AWT_WM_NONREPARENTING=1 	# Fix for Java applications in dwm

	# Learn less how to displaying man pages in colour via change the termcap info
		export LESS=-R
		export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
		export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
		export LESS_TERMCAP_me="$(printf '%b' '[0m')"
		export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
		export LESS_TERMCAP_se="$(printf '%b' '[0m')"
		export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
		export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts ~/.shortcuts_error 2>$1 # >/dev/null 2>&1


exec echo ".zprofile_started" >> ~/start &


# Luke's version:
	# Start graphical server on user's current tty if not already running.
		#[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
# Arch's wiki version:
	# You can replace the -eq with -le 3 (for vt1 to vt3) if you want to use
	# graphical logins on more than one virtual terminal.
	# The exec command ensures that the user is logged out when the X server exits.
	#
		[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx "$XINITRC" 2>~/.xsession.errors
