#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# It also is sourced via xinitrc.

xrandr --output DP-0 --primary --mode 3440x1440 --rate 100.00 --right-of HDMI-0

 	xrandr --dpi 144	# Set DPI. User may want to use a larger number for larger screens.
	setbg &			# set the background with the `setbg` script
	remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#	xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

# autostart some programs
 	xcompmgr 	&
	dunst 		&
	unclutter	&
# MPD daemon start (if no other user instance exists)
	mpd	--no-daemon &
